### PR TITLE
feat: add option to send notifications on pet received

### PR DESCRIPTION
**Pull request by delps1001**
adds the option to send a notification on pet received :)

### CODE REVIEW

**Comment by delps1001** [comment]
@WilliamWinterDev a new PR! :)

**Comment by WilliamWinterDev** [comment]
@delps1001 I wonder if we can make it say which pet the user got within the discord message 🤔

**Comment by delps1001** [comment]
> @delps1001 I wonder if we can make it say which pet the user got within the discord message 🤔

I'm unsure of a good way to do it, because the chat message doesn't contain the pet's name... We could potentially scan the player's inventory/check their follower

**Comment by delps1001** [comment]
I can look into it, but it's unfortunate because it's somewhat difficult to test :D

**Comment by delps1001** [comment]
@WilliamWinterDev I talked in the runelite dev discord with some folks and unfortunately it's kind of pain to get the pet name.

We'd need to maintain a set of inventory item ids (could be only for the pets) and compare to the previous game tick. we'd al also need to check the player's pet varbit and maintain a map of pet varbits to get a name. This would greatly increase the complexity of the plugin just for the pet name. To me this doesn't seem worth it, but I'd like to hear what your thoughts are.

**Comment by delps1001** [comment]
I also looked into just utilizing the collection log, but there isn't an easy way to get collection log entries without the player manually opening it.

**Comment by WilliamWinterDev** [comment]
I would tend to agree that its probably not worth it tbh @delps1001 , will merge now!

**Pull request merged**
